FAILED test/test_blocks_on_demand.py::test_invokable_on_pending_block - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_block_number.py::test_block_number_incremented[run_devnet_in_background0] - AssertionError: assert 2 == (0 + 1)
FAILED test/test_account.py::test_invoking_another_contract - TypeError: int() can't convert non-string with explicit base
FAILED test/test_calls_by_block_id.py::test_call - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:46059/feeder_gateway/call_contract?blockNumber=1. Status code: 500; text: {"code":"StarknetErrorCode...
FAILED test/test_endpoints.py::test_deploy_with_complete_request_data - AssertionError: assert {'code', 'message'} == {'address', '...saction_hash'}
FAILED test/test_endpoints.py::test_call_with_complete_request_data - AssertionError: assert {'code': 'Sta...ot deployed.'} == {'result': ['0xa']}
FAILED test/test_account.py::test_estimated_fee - TypeError: int() can't convert non-string with explicit base
FAILED test/test_blocks_on_demand.py::test_estimation_works_after_block_creation - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_block_number.py::test_block_number_incremented[run_devnet_in_background1] - AssertionError: assert 2 == (0 + 1)
FAILED test/test_account.py::test_low_max_fee - TypeError: int() can't convert non-string with explicit base
FAILED test/test_blocks_on_demand.py::test_calling_works_after_block_creation - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_account.py::test_sufficient_max_fee - TypeError: int() can't convert non-string with explicit base
FAILED test/test_chain_id_cli_params.py::test_deploy_and_invoke[run_devnet_in_background0-StarknetChainId.MAINNET] - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:47251/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_deploy.py::test_deploy_account - TypeError: int() can't convert non-string with explicit base
FAILED test/test_block_number.py::test_block_number_incremented_on_declare - AssertionError: assert 2 == (0 + 1)
FAILED test/test_blocks_on_demand.py::test_getting_next_block - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_account.py::test_insufficient_balance - TypeError: int() can't convert non-string with explicit base
FAILED test/test_deploy.py::test_deploy_through_deployer_constructor - TypeError: int() can't convert non-string with explicit base
FAILED test/test_account.py::test_multicall - TypeError: int() can't convert non-string with explicit base
FAILED test/test_block_number.py::test_block_number_not_incremented_if_deploy_fails - AssertionError: assert 2 == (0 + 1)
FAILED test/test_blocks_on_demand.py::test_pending_block - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_calls_by_block_id.py::test_forked - assert 1005 == (1000 + 4)
FAILED test/test_block_number.py::test_block_number_not_incremented_if_invoke_fails - AssertionError: assert 2 == (0 + 1)
FAILED test/test_blocks_on_demand.py::test_pending_block_traces - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_chain_id_cli_params.py::test_deploy_and_invoke[run_devnet_in_background2-StarknetChainId.TESTNET2] - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:47251/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_fork.py::test_forking_devnet_with_account_on_origin - requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=43945): Max retries exceeded with url: /feeder_gateway/get_nonce?contractAddress=0x1caf2df5ed5dde1ae3faef4acd725...
FAILED test/test_endpoints.py::test_get_transaction_trace_of_rejected - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:54435/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_calls_by_block_id.py::test_after_restart - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:46059/feeder_gateway/call_contract?blockNumber=1. Status code: 500; text: {"code":"StarknetErrorCode...
FAILED test/test_account.py::test_get_nonce_endpoint - TypeError: int() can't convert non-string with explicit base
FAILED test/test_fork.py::test_forking_devnet_with_account_on_fork - requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=43945): Max retries exceeded with url: /feeder_gateway/get_nonce?contractAddress=0x1caf2df5ed5dde1ae3faef4acd725...
FAILED test/test_blocks_on_demand.py::test_pending_state_update - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_calls_by_block_id.py::test_old_block_generated_on_demand - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:46059/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_blocks_on_demand.py::test_events - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_fee_token.py::test_increase_balance - TypeError: int() can't convert non-string with explicit base
FAILED test/test_calls_by_block_id.py::test_getting_storage_at_old_block - AssertionError: 
FAILED test/test_blocks_on_demand.py::test_endpoint_if_no_pending_after_creation - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_blocks_on_demand.py::test_endpoint_if_some_pending - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:33949/feeder_gateway/simulate_transaction?blockNumber=pending. Status code: 500; text: {"code":"Star...
FAILED test/test_postman.py::test_postman - AssertionError: assert '0x034c5e112f...00679e9a8affc' == '0x34c5e112fc...00679e9a8affc'
FAILED test/test_transaction_trace.py::test_deploy_transaction_trace - AssertionError: assert ['0x7a5ac8328...69a219b3cc32'] == []
FAILED test/test_transaction_trace.py::test_get_block_traces - AssertionError: assert 321126931779230961...7225554428687084372 == 273165223638053295...8270544889460431331
FAILED test/rpc/test_rpc_call.py::test_call[hash] - KeyError: 'address'
FAILED test/rpc/test_rpc_call.py::test_call[number] - KeyError: 'address'
FAILED test/rpc/test_rpc_class.py::test_get_class_at - KeyError: 'address'
FAILED test/rpc/test_rpc_call.py::test_call[tag] - KeyError: 'address'
FAILED test/test_fork.py::test_deploy_account - TypeError: int() can't convert non-string with explicit base
FAILED test/test_state_update.py::test_block_number - AssertionError: 
FAILED test/rpc/test_rpc_call.py::test_call[tag_pending] - KeyError: 'address'
FAILED test/test_timestamps.py::test_set_time - assert 1677160195 == (1677073789 + 86400)
FAILED test/test_dump.py::test_calling_old_state_after_load - test.util.ReturnCodeAssertionError: Got BadRequest while trying to access http://127.0.0.1:42533/feeder_gateway/call_contract?blockNumber=1. Status code: 500; text: {"code":"StarknetErrorCode...
FAILED test/rpc/test_rpc_misc.py::test_get_state_update - AssertionError: assert [] == ['0x0494eea8d...2b9ec51dd167']
FAILED test/rpc/test_rpc_call.py::test_call_raises_on_incorrect_selector - KeyError: 'address'
FAILED test/rpc/test_rpc_estimate_fee.py::test_estimate_happy_path_v0[run_devnet_in_background0] - TypeError: int() can't convert non-string with explicit base
FAILED test/rpc/test_rpc_call.py::test_call_raises_on_invalid_calldata[calldata0] - KeyError: 'address'
FAILED test/rpc/test_rpc_call.py::test_call_raises_on_invalid_calldata[calldata1] - KeyError: 'address'
FAILED test/rpc/test_rpc_transactions.py::test_get_transaction_by_hash_deploy - KeyError: 'transaction_hash'
FAILED test/rpc/test_rpc_estimate_fee.py::test_estimate_happy_path[run_devnet_in_background0] - TypeError: int() can't convert non-string with explicit base
FAILED test/rpc/test_rpc_call.py::test_call_raises_on_invalid_calldata[calldata2] - KeyError: 'address'
FAILED test/rpc/test_rpc_call.py::test_call_raises_on_incorrect_block_hash - KeyError: 'address'
FAILED test/rpc/test_rpc_call.py::test_call_on_old_block - KeyError: 'address'
FAILED test/test_state_update.py::test_declaration_and_deployment - AssertionError: assert [] == ['0x494eea8db...2b9ec51dd167']
FAILED test/rpc/test_rpc_storage.py::test_get_storage_at - KeyError: 'address'
FAILED test/rpc/test_rpc_estimate_fee.py::test_estimate_fee_with_invalid_call_data[run_devnet_in_background0] - TypeError: int() can't convert non-string with explicit base
FAILED test/rpc/test_rpc_storage.py::test_get_storage_at_old_block - KeyError: 'address'
FAILED test/rpc/test_rpc_storage.py::test_get_storage_at_raises_on_incorrect_key - KeyError: 'address'
FAILED test/rpc/test_rpc_estimate_fee.py::test_estimate_fee_with_invalid_message_selector - TypeError: int() can't convert non-string with explicit base
FAILED test/rpc/test_rpc_storage.py::test_get_storage_at_raises_on_incorrect_block_id - KeyError: 'address'
FAILED test/test_timestamps.py::test_lite_mode_compatibility - assert 106 == 100
FAILED test/rpc/test_rpc_transactions.py::test_get_transaction_by_block_id_and_index - KeyError: 'transaction_hash'
FAILED test/rpc/test_rpc_transactions.py::test_get_transaction_by_block_id_and_index_raises_on_incorrect_index - KeyError: 'transaction_hash'
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background0-input_data0-expected_data0] - AssertionError: assert 2 == 3
FAILED test/rpc/test_rpc_transactions.py::test_get_deploy_transaction_receipt - KeyError: 'transaction_hash'
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background1-input_data1-expected_data1] - AssertionError: assert 2 == 3
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background2-input_data2-expected_data2] - assert "['0x01caf2df...800', '0x00']" == "['0x0347be35...800', '0x00']"
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background3-input_data3-expected_data3] - assert "['0x0347be35...800', '0x00']" == "['0x0347be35...800', '0x00']"
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background4-input_data4-expected_data4] - assert "['0x01caf2df...800', '0x00']" == "['0x0347be35...800', '0x00']"
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background5-input_data5-expected_data5] - assert "['0x01caf2df...800', '0x00']" == "['0x0347be35...800', '0x00']"
FAILED test/rpc/test_rpc_misc.py::test_get_events[run_devnet_in_background6-input_data6-expected_data6] - assert "['0x0347be35...800', '0x00']" == "['0x0347be35...800', '0x00']"
FAILED test/rpc/test_rpc_misc.py::test_get_nonce - TypeError: int() can't convert non-string with explicit base
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[hash] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[number] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[tag] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_tx_hashes[tag_pending] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_txs[hash] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_txs[number] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_txs[tag] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_with_txs[tag_pending] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_class.py::test_get_class - KeyError: 'address'
ERROR test/rpc/test_rpc_class.py::test_get_class_hash_at - KeyError: 'address'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_transaction_count[hash] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_transaction_count[number] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_transaction_count[tag] - KeyError: 'transaction_hash'
ERROR test/rpc/test_rpc_blocks.py::test_get_block_transaction_count[tag_pending] - KeyError: 'transaction_hash'